name: Android Test

on:
  push:
    branches: [ "master", "stable-ui-phase1" ]
  pull_request:
    branches: [ "master", "stable-ui-phase1" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run unit tests
      run: ./gradlew test

    - name: Run instrumented tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew connectedCheck

    - name: Upload test reports
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: app/build/reports/
